/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.interview


/**
Create a basic calculator that takes inputs as strings and returns a calculated value

The input should follow the flow of a four-function calculator - each input is entered
as a single entry with an operator and operand like the examples below.

Entering an operand without an operator should be enterpreted as equals.

The order of operations should be interpreted in the input order, not PEMDAS hierarchy.
 */
fun main(args: Array<String>) {
    val calculator = Calculator()
    println(calculator.input("5+"))
    println(calculator.input("5*"))
    println(calculator.input("10="))
    println("Expected: 100")

    println(calculator.input("3+"))
    println(calculator.input("4"))
    println("Expected: 7")

    println(calculator.input("4+"))
    println(calculator.input("6/"))
    println(calculator.input("2="))
    println("Expected: 5")
}

class Calculator {
    fun input(input: String): String {
        return ""
    }
}